export enum MovementPattern {
  HORIZONTAL_PUSH = 'HORIZONTAL_PUSH',
  VERTICAL_PUSH = 'VERTICAL_PUSH',
  HORIZONTAL_PULL = 'HORIZONTAL_PULL',
  VERTICAL_PULL = 'VERTICAL_PULL',
  SQUAT = 'SQUAT',
  HIP_HINGE = 'HIP_HINGE',
  CARRY = 'CARRY',
  ISOLATION = 'ISOLATION',
}
