export enum MovementPattern {
  HORIZONTAL_PUSH = 'HORIZONTAL_PUSH',
  VERTICAL_PUSH = 'VERTICAL_PUSH',
  HORIZONTAL_PULL = 'HORIZONTAL_PULL',
  VERTICAL_PULL = 'VERTICAL_PULL',
  KNEE_DOMINANT = 'KNEE_DOMINANT',
  HIP_HINGE = 'HIP_HINGE',
  CORE = 'CORE',
  CARRY = 'CARRY',
}
